# python
#
# SConscript file for Example class

import os, sys, re

Import(['env'])
objs = []

dirs = []

headers = [ Split("""
  CoordinateData3D.h
  CoordinateSystem3D.h
""") ]

sources = [ Split("""
  CoordinateData3D.cpp
  CoordinateSystem3D.cpp
""") ]

for dir in dirs:
  o = SConscript(
      dir + os.sep + 'SConscript',
      exports=['env']
      )
  objs.append(o)


for source in sources:
  objs.append(env.Object(source))


Return('objs')

